name: Build the app

on: push

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2

  #     - name: Setup Scala
  #       uses: japgolly/setup-everything-scala@v3.1
  #       with:
  #         java-version: 'adopt:1.11.0-11'
  #         node-version: '16.7.0'

  #     - name: Cache compiled code
  #       uses: actions/cache@v3
  #       with:
  #         path: |
  #           **/target/
  #           /home/runner/.ivy2/local
  #         key: compiled-code-cache-${{ hashFiles('**/build.sbt') }}
  #         restore-keys: compiled-code-cache-

  #     - name: Check code format
  #       run: sbt scalafmtCheckAll

  #     - name: Compile
  #       run: CI=true sbt compile

  #     - name: Run tests
  #       run: CI=true sbt test

  #     - name: Test summary
  #       if: always() # Always run, even if previous steps failed
  #       uses: test-summary/action@v2
  #       with:
  #         paths: "**/target/test-reports/*.xml"

  #     - name: Prepare web build
  #       run: sbt web/build

  #     - name: Prepare server build
  #       run: sbt server/dist

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "11"
      - uses: snyk/actions/setup@master
      - name: Snyk test
        run: snyk test --sarif-file-output=snyk.sarif --all-projects
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
